import ScanbotSDK, {Page} from 'react-native-scanbot-sdk';

async function createDocument() {
  /** Create a document with an uuid */
  const document = ScanbotSDK.Document.createDocument({});
}

async function createDocumentWithPages(imageFileUris: string[]) {
  /**
   * Create a document with an uuid
   * Add images from `imageFileUris` as document pages
   */
  const document = ScanbotSDK.Document.createDocument({
    imageFileUris: imageFileUris,
  });
}

async function loadDocument(documentID: string) {
  /** Load a document from storage by ID */
  const document = await ScanbotSDK.Document.loadDocument(documentID);
}

async function storedDocumentUUIDs() {
  /** Retrieve all the document ids from the storage */
  const {documentIDs} = await ScanbotSDK.Document.storedDocumentIDs();
}

async function reorderDocumentPages(documentID: string) {
  /** Load a document from storage by ID */
  const document = await ScanbotSDK.Document.loadDocument(documentID);
  /** Swap the first and last page of the document */
  const documentWithReorderedPages = await ScanbotSDK.Document.movePage({
    documentID: document.uuid,
    fromIndex: 0,
    toIndex: document.pages.length - 1,
  });
}

async function removeAllPagesFromDocument(documentID: string) {
  /** Remove all the pages from a document */
  const documentWithRemovedPages = await ScanbotSDK.Document.removeAllPages(
    documentID,
  );
}

async function deleteDocument(documentID: string) {
  /** Delete a document from storage along with the document's PDF and TIFF files */
  await ScanbotSDK.Document.deleteDocument(documentID);
}

async function cleanup() {
  /** Removes all the files generated by ScanbotSDK including the documents */
  await ScanbotSDK.cleanup();
}
