require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ScanbotSDKExampleReact' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  # Pod for Scanbot SDK React Native Module
  pod 'RNScanbotSDK/ALL', :path => '../node_modules/react-native-scanbot-sdk'

  pod 'RNScanbotSDK', :path => '../node_modules/react-native-scanbot-sdk'

  target 'ScanbotSDKExampleReactTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ScanbotSDKExampleReact-tvOS' do
  # Pods for ScanbotSDKExampleReact-tvOS

  target 'ScanbotSDKExampleReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
