require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'ScanbotSDKExampleReact' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  # Pod for Scanbot SDK React Native Module
  pod 'RNScanbotSDK/ALL', :path => '../node_modules/react-native-scanbot-sdk'

  use_flipper!()
  
  post_install do |installer|
    react_native_post_install(installer)
  end
end
